In [1]:
import numpy as np
a = np.random.rand(3,3)
b = np.random.randn(2,2)
print(a)
print(b)

[[0.62923628 0.26483606 0.99983678]
 [0.73942718 0.77891976 0.00149867]
 [0.98405062 0.76491624 0.65796964]]
[[-1.54296984 -0.62004518]
 [-0.91792221  0.80535937]]
