In [1]:
import  numpy as np
m = np.array([[3, 4, 5], [1, 2, 2], [4, 3, 1]])
print('Given matrix is:')
print(m)
result = np.linalg.det(m)
print('Determinant of the given matrix: ')
print(int(result))

Given matrix is:
[[3 4 5]
 [1 2 2]
 [4 3 1]]
Determinant of the given matrix: 
-8
