In [1]:
import numpy as np
a = np.arange(0, 10, 2)
print(a)
b = np.linspace(0, 1, 6) 
print(b)
c = np.ones((3,3)) #Creating matrix of only one's
print(c)
d = np.zeros((3,3)) #Creatinng matrix of only zero's
print(d)
e = np.eye(3,3) #Creating identity matrix
print(e)
f = np.diag([1, 2, 3]) #Creting diagonal matrix
print(f)

[0 2 4 6 8]
[0.  0.2 0.4 0.6 0.8 1. ]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
