In [1]:
import numpy as np
m = np.array([[3, 4, 5], [1, 2, 2], [4, 3, 1]])
print('Given matrix is:')
print(m)
result = np.linalg.inv(m)
print('Inverse of the given matrix: ')
print(result)

Given matrix is:
[[3 4 5]
 [1 2 2]
 [4 3 1]]
Inverse of the given matrix: 
[[ 0.44444444 -1.22222222  0.22222222]
 [-0.77777778  1.88888889  0.11111111]
 [ 0.55555556 -0.77777778 -0.22222222]]
