In [1]:
import numpy as np
a = np.array([[3, 6, 7], [5, -3, 0]])
b = np.array([[1, 1], [2, 1], [3, -3]])
print('The first initialized vector is: ')
print(a)
print('The second initialized vector is: ')
print(b)

The first initialized vector is: 
[[ 3  6  7]
 [ 5 -3  0]]
The second initialized vector is: 
[[ 1  1]
 [ 2  1]
 [ 3 -3]]
