In [1]:
import numpy as np
row1 = int(input('Enter the number of rows: '))
col1 = int(input('Enter the number of columns: '))
print('Enter the entries in a single line (seperated by space):')
entries = list(map(int, input().split()))
matrix1 = np.array(entries).reshape(row1, col1)
print(matrix1)

row2 = int(input('Enter the number of rows: '))
col2 = int(input('Enter the number of columns: '))
print('Enter the entries in a single line (seperated by space):')
entries = list(map(int, input().split()))
matrix2 = np.array(entries).reshape(row2, col2)
print(matrix2)

x = matrix1.dot(matrix2)
print('Multiplication of the two matrix is: ')
print(x)

Enter the entries in a single line (seperated by space):
[[1 2]
 [3 4]
 [5 6]]
Enter the entries in a single line (seperated by space):
[[1 2 3]
 [4 5 6]]
Multiplication of the two matrix is: 
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
