In [1]:
import numpy as np
a = np.array([[3, 6, 7], [5, -3, 0]])
print('The first initialized vector is: ')
print(a)
print('The transpose of matrix {a}')
print(a.transpose())

The first initialized vector is: 
[[ 3  6  7]
 [ 5 -3  0]]
The transpose of matrix {a}
[[ 3  5]
 [ 6 -3]
 [ 7  0]]
